### PR TITLE
Update to allow swipe to close

### PR DESCRIPTION
**Pull request by ljknight**
This plugin has been great, we've been using it at my company for a mobile web app. One usability feature that we felt was missing was the ability to swipe to close, instead of only the tap. Hope this works - thanks for your work on this.

### CODE REVIEW

**Comment by ljknight** [comment]
@silentcloud - based on how these tests are failing it seems like you intentionally set up the swipe to only swipe right or left. Is it ok to have it swipe both ways, or do you think it should be passed in as an option?

**Comment by silentcloud** [comment]
@ljknight  when `left=[]` or `right=[]` ,  swipe to direction will  trigger `open()` function;

for example: 
```
<Swipe left=[{...}, {...}] onOpen={() => {}} />
```

when swipe to left direction, `open()` will be triggered，in fact it should not be triggered

**Comment by ljknight** [comment]
@silentcloud thanks for the reply - I'm not sure I understand what you mean

**Comment by silentcloud** [comment]
test

**Comment by ljknight** [comment]
@silentcloud - added an update that won't pass the linter, but it fixes the issue my initial commit didn't take into consideration. let me know what you think.

**Comment by silentcloud** [comment]
allow swipe to close: 78a5fe111974da0afa5f0ff5239cc655d60c9bca

**Pull request closed without merging**
